version: "3.9"

services:
  oracle:
    image: container-registry.oracle.com/database/express:latest
    container_name: app-prepaga-db
    ports:
      - "1521:1521"
    environment:
      ORACLE_PWD: 123456
    volumes:
      - prepaga-db-data:/opt/oracle/oradata

volumes:
  prepaga-db-data:
